const AllProducts = [
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
  {
    id: "UbzNvaJzzYoJYnciRv1Ttg==",
    name: "RedSwitches Instant Bare-Metal Server custom #001",
    desc: {
      CPU: "1x  Intel Xeon E3-1230",
      Chassis: "HP DL120G7",
      Cores: "4 Cores - 8 Threads @3.20 Ghz",
      Location: "Frankfurt",
      Network: "1Gbps",
      RAM: "16GB DDR3",
      Storage: "4x1TB SATA",
      Traffic: "30 TB",
      filterCores: "4",
      filterLocation: "Frankfurt",
      filterRAM: "16",
      filterStorage: "sata",
    },
    minprice: { amount: "50.40", billingcycle: "monthly", setupfee: 0 },
  },
]

export default AllProducts
